name: Despertador do Robô IA 24h

on:
  schedule:
    # O robô vai "acordar" no início de cada hora (ex: 13:00, 14:00, 15:00...)
    - cron: '0 * * * *'
  workflow_dispatch: # Permite que você rode manualmente se quiser testar

jobs:
  visitar_painel:
    runs-on: ubuntu-latest
    steps:
      - name: Acessando o Painel via Nuvem
        run: |
          curl -sS "https://paineliapy-xhsluoqusu5vmbc9dxjzxi.streamlit.app" > /dev/null
          echo "Visita realizada com sucesso às $(date)"
